name: Run-Minute

on:
  schedule:
    - cron: '*/1 * * * *'
  workflow_dispatch:


jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Run Script
      env:
        WPE_SSHG_KEY_PRIVATE: ${{secrets.WPE_SSHG_KEY_PRIVATE}}
      run: |
        chmod +x script.sh
        ./script.sh
      


        
