name: Run-Minute

on:
  workflow_dispatch:
  schedule:
    - cron: '* * * * *'

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      env:
        WPE_SSHG_KEY_PRIVATE: ${{ secrets.WPE_SSHG_KEY_PRIVATE }}
    - name: Run Script
      run: |
        chmod +x script.sh
        ./script.sh
      


        
